language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
before_script:
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar -xvf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1 && ./configure && make && sudo make install && sudo ldconfig && cd ..
script:
  - sbt clean buffered-config-test:test invalid-config-test:test coverage test coverageReport && sbt coverageAggregate
after_success:
  - sbt coveralls
